// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyLoTrinhXeBuyt.Data;

#nullable disable

namespace QuanLyLoTrinhXeBuyt.Migrations
{
    [DbContext(typeof(QLLTXBContext))]
    [Migration("20250428055010_KhoiTaoCSDL")]
    partial class KhoiTaoCSDL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyLoTrinhXeBuyt.Data.ChuyenXe", b =>
                {
                    b.Property<int>("ChuyenXeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChuyenXeID"));

                    b.Property<string>("DiemXuatPhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianDen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianDi")
                        .HasColumnType("datetime2");

                    b.Property<int>("TuyenXeID")
                        .HasColumnType("int");

                    b.Property<int>("XeID")
                        .HasColumnType("int");

                    b.HasKey("ChuyenXeID");

                    b.HasIndex("TuyenXeID");

                    b.HasIndex("XeID");

                    b.ToTable("ChuyenXe");
                });

            modelBuilder.Entity("QuanLyLoTrinhXeBuyt.Data.NhanVien", b =>
                {
                    b.Property<int>("NhanVienID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NhanVienID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QuanLyLoTrinhXeBuyt.Data.PhanCong", b =>
                {
                    b.Property<int>("PhanCongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhanCongID"));

                    b.Property<DateTime>("NgayLamViec")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int>("XeID")
                        .HasColumnType("int");

                    b.HasKey("PhanCongID");

                    b.HasIndex("NhanVienID");

                    b.HasIndex("XeID");

                    b.ToTable("PhanCong");
                });

            modelBuilder.Entity("QuanLyLoTrinhXeBuyt.Data.TaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiKhoanID"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<string>("QuyenHan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaiKhoanID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyLoTrinhXeBuyt.Data.TramXe", b =>
                {
                    b.Property<int>("TramXeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TramXeID"));

                    b.Property<string>("TenTramXe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TramXeID");

                    b.ToTable("TramXe");
                });

            modelBuilder.Entity("QuanLyLoTrinhXeBuyt.Data.TuyenXe", b =>
                {
                    b.Property<int>("TuyenXeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TuyenXeID"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTuyen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TuyenXeID");

                    b.ToTable("TuyenXe");
                });

            modelBuilder.Entity("QuanLyLoTrinhXeBuyt.Data.TuyenXe_ChiTiet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("TramXeID")
                        .HasColumnType("int");

                    b.Property<int>("TuyenXeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TramXeID");

                    b.HasIndex("TuyenXeID");

                    b.ToTable("TuyenXe_ChiTiet");
                });

            modelBuilder.Entity("QuanLyLoTrinhXeBuyt.Data.XeBuyt", b =>
                {
                    b.Property<int>("XeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("XeID"));

                    b.Property<string>("BienSo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("XeID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("XeBuyt");
                });

            modelBuilder.Entity("QuanLyLoTrinhXeBuyt.Data.ChuyenXe", b =>
                {
                    b.HasOne("QuanLyLoTrinhXeBuyt.Data.TuyenXe", "TuyenXe")
                        .WithMany("ChuyenXe")
                        .HasForeignKey("TuyenXeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyLoTrinhXeBuyt.Data.XeBuyt", "Xe")
                        .WithMany()
                        .HasForeignKey("XeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TuyenXe");

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLyLoTrinhXeBuyt.Data.PhanCong", b =>
                {
                    b.HasOne("QuanLyLoTrinhXeBuyt.Data.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyLoTrinhXeBuyt.Data.XeBuyt", "Xe")
                        .WithMany()
                        .HasForeignKey("XeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLyLoTrinhXeBuyt.Data.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyLoTrinhXeBuyt.Data.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyLoTrinhXeBuyt.Data.TuyenXe_ChiTiet", b =>
                {
                    b.HasOne("QuanLyLoTrinhXeBuyt.Data.TramXe", "TramXe")
                        .WithMany("TuyenXe_ChiTiet")
                        .HasForeignKey("TramXeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyLoTrinhXeBuyt.Data.TuyenXe", "TuyenXe")
                        .WithMany("TuyenXe_DiemDung")
                        .HasForeignKey("TuyenXeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TramXe");

                    b.Navigation("TuyenXe");
                });

            modelBuilder.Entity("QuanLyLoTrinhXeBuyt.Data.XeBuyt", b =>
                {
                    b.HasOne("QuanLyLoTrinhXeBuyt.Data.NhanVien", null)
                        .WithMany("XeBuyt")
                        .HasForeignKey("NhanVienID");
                });

            modelBuilder.Entity("QuanLyLoTrinhXeBuyt.Data.NhanVien", b =>
                {
                    b.Navigation("XeBuyt");
                });

            modelBuilder.Entity("QuanLyLoTrinhXeBuyt.Data.TramXe", b =>
                {
                    b.Navigation("TuyenXe_ChiTiet");
                });

            modelBuilder.Entity("QuanLyLoTrinhXeBuyt.Data.TuyenXe", b =>
                {
                    b.Navigation("ChuyenXe");

                    b.Navigation("TuyenXe_DiemDung");
                });
#pragma warning restore 612, 618
        }
    }
}
